//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpsApi.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class KonumTablo
    {
        public int id { get; set; }
        public string latData { get; set; }
        public string longData { get; set; }
        public string daeData { get; set; }
    }
}
